import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import { Toaster } from "sonner";

import theme from "./theme";
import { SocketProvider } from "@contexts";

import "./globals.css";

import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning>
        <AppRouterCacheProvider options={{ key: "css" }}>
          <SocketProvider>
            <ThemeProvider theme={theme}>{children}</ThemeProvider>
          </SocketProvider>
        </AppRouterCacheProvider>
        <Toaster position="top-right" expand={true} richColors closeButton />
        <Script src="/service-worker.js" />
      </body>
    </html>
  );
}
