import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import { Toaster } from "sonner";

import { cn } from "@/lib/utils";
import { SocketProvider } from "@contexts";

import "./globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <SocketProvider>{children}</SocketProvider>
        <Toaster position="top-right" expand={true} richColors closeButton />
      </body>
    </html>
  );
}
